# Base16 Atelier Savanna Light
# Author: Bram de Haan (http://atelierbramdehaan.nl)
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_fg = "#5f6d64"
info_fg = "#5f6d64"
good_fg = "#489963"
warning_fg = "#a07e3b"
critical_fg = "#b16139"
