# Base16 Solarized Light
# Author: Ethan Schoonover (modified by aramisgithub)
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_fg = "#657b83"
info_fg = "#657b83"
good_fg = "#859900"
warning_fg = "#b58900"
critical_fg = "#dc322f"
