# Base16 Grayscale Dark
# Author: Alexandre Gavioli (https://github.com/Alexx2/)
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_fg = "#ababab"
info_fg = "#ababab"
good_fg = "#8e8e8e"
warning_fg = "#a0a0a0"
critical_fg = "#7c7c7c"
