# Base16 Material Palenight
# Author: Nate Peterson
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_fg = "#8796b0"
info_fg = "#8796b0"
good_fg = "#c3e88d"
warning_fg = "#ffcb6b"
critical_fg = "#f07178"
