# Base16 Tokyo Night Terminal Storm
# Author: Michaël Ball
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_fg = "#787c99"
info_fg = "#787c99"
good_fg = "#41a6b5"
warning_fg = "#e0af68"
critical_fg = "#f7768e"
