# Base16 Windows High Contrast
# Author: Fergus Collins (https://github.com/C-Fergus)
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_fg = "#a2a2a2"
info_fg = "#a2a2a2"
good_fg = "#54fc54"
warning_fg = "#fcfc54"
critical_fg = "#fc5454"
