# Base16 PhD
# Author: Hennig Hasemann (http://leetless.de/vim.html)
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_fg = "#9a99a3"
info_fg = "#9a99a3"
good_fg = "#99bf52"
warning_fg = "#fbd461"
critical_fg = "#d07346"
