# Base16 Tomorrow Night Eighties
# Author: Chris Kempson (http://chriskempson.com)
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_fg = "#b4b7b4"
info_fg = "#b4b7b4"
good_fg = "#99cc99"
warning_fg = "#ffcc66"
critical_fg = "#f2777a"
