# Base16 Equilibrium Gray Dark
# Author: Carlo Abelli
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_fg = "#919191"
info_fg = "#919191"
good_fg = "#7f8b00"
warning_fg = "#bb8801"
critical_fg = "#f04339"
