# Base16 Black Metal
# Author: metalelf0 (https://github.com/metalelf0)
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_fg = "#999999"
info_fg = "#999999"
good_fg = "#dd9999"
warning_fg = "#a06666"
critical_fg = "#5f8787"
