# Base16 Tokyo Night Light
# Author: Michaël Ball
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_fg = "#4c505e"
info_fg = "#4c505e"
good_fg = "#485e30"
warning_fg = "#166775"
critical_fg = "#343b58"
