# Base16 Tokyo City Terminal Dark
# Author: Michaël Ball
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_fg = "#b7c5d3"
info_fg = "#b7c5d3"
good_fg = "#8bd49c"
warning_fg = "#ebbf83"
critical_fg = "#d95468"
