# Base16 Atelier Dune Light
# Author: Bram de Haan (http://atelierbramdehaan.nl)
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_fg = "#7d7a68"
info_fg = "#7d7a68"
good_fg = "#60ac39"
warning_fg = "#ae9513"
critical_fg = "#d73737"
