# Base16 Porple
# Author: Niek den Breeje (https://github.com/AuditeMarlow)
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_fg = "#b8b8b8"
info_fg = "#b8b8b8"
good_fg = "#95c76f"
warning_fg = "#efa16b"
critical_fg = "#f84547"
