# Base16 Unikitty Dark
# Author: Josh W Lewis (@joshwlewis)
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_fg = "#9f9da2"
info_fg = "#9f9da2"
good_fg = "#17ad98"
warning_fg = "#dc8a0e"
critical_fg = "#d8137f"
