# Base16 Synth Midnight Terminal Dark
# Author: Michaël Ball (http://github.com/michael-ball/)
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_fg = "#a3a5a6"
info_fg = "#a3a5a6"
good_fg = "#06ea61"
warning_fg = "#c9d364"
critical_fg = "#b53b50"
