# Base16 Black Metal (Immortal)
# Author: metalelf0 (https://github.com/metalelf0)
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_fg = "#999999"
info_fg = "#999999"
good_fg = "#7799bb"
warning_fg = "#556677"
critical_fg = "#5f8787"
