# Base16 Colors
# Author: mrmrs (http://clrs.cc)
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_fg = "#999999"
info_fg = "#999999"
good_fg = "#2ecc40"
warning_fg = "#ffdc00"
critical_fg = "#ff4136"
