# Base16 Gigavolt
# Author: Aidan Swope (http://github.com/Whillikers)
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_fg = "#cad3ff"
info_fg = "#cad3ff"
good_fg = "#f2e6a9"
warning_fg = "#ffdc2d"
critical_fg = "#ff661a"
