# Base16 Shades of Purple
# Author: Iolar Demartini Junior (http://github.com/demartini) based on Shades of Purple Theme (https://github.com/ahmadawais/shades-of-purple-vscode).
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_fg = "#6871ff"
info_fg = "#6871ff"
good_fg = "#3ad900"
warning_fg = "#ffe700"
critical_fg = "#d90429"
