# Base16 PaperColor Dark
# Author: Jon Leopard (http://github.com/jonleopard) based on PaperColor Theme (https://github.com/NLKNguyen/papercolor-theme)
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_fg = "#5fafd7"
info_fg = "#5fafd7"
good_fg = "#af87d7"
warning_fg = "#afd700"
critical_fg = "#585858"
