# Base16 Black Metal (Venom)
# Author: metalelf0 (https://github.com/metalelf0)
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_fg = "#999999"
info_fg = "#999999"
good_fg = "#f8f7f2"
warning_fg = "#79241f"
critical_fg = "#5f8787"
