# Base16 Summerfruit Dark
# Author: Christopher Corley (http://christop.club/)
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_fg = "#b0b0b0"
info_fg = "#b0b0b0"
good_fg = "#00c918"
warning_fg = "#aba800"
critical_fg = "#ff0086"
