# Base16 Brush Trees
# Author: Abraham White &lt;abelincoln.white@gmail.com&gt;
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_fg = "#8299a1"
info_fg = "#8299a1"
good_fg = "#87b386"
warning_fg = "#aab386"
critical_fg = "#b38686"
