# Base16 OceanicNext
# Author: https://github.com/voronianski/oceanic-next-color-scheme
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_fg = "#a7adba"
info_fg = "#a7adba"
good_fg = "#99c794"
warning_fg = "#fac863"
critical_fg = "#ec5f67"
