# Base16 Silk Light (powerline)
# Author: Gabriel Fontes (https://github.com/Misterio77)
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_bg = "#ccd4d3"
idle_fg = "#385156"
info_bg = "#39aac9"
info_fg = "#e9f1ef"
good_bg = "#6ca38c"
good_fg = "#e9f1ef"
warning_bg = "#cfad25"
warning_fg = "#e9f1ef"
critical_bg = "#cf432e"
critical_fg = "#e9f1ef"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
