# Base16 Heetch Light (powerline)
# Author: Geoffrey Teale (tealeg@gmail.com)
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_bg = "#392551"
idle_fg = "#5a496e"
info_bg = "#47f9f5"
info_fg = "#feffff"
good_bg = "#f80059"
good_fg = "#feffff"
warning_bg = "#5ba2b6"
warning_fg = "#feffff"
critical_bg = "#27d9d5"
critical_fg = "#feffff"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
