# Base16 Gruvbox Material Dark, Hard (powerline)
# Author: Mayush Kumar (https://github.com/MayushKumar), sainnhe (https://github.com/sainnhe/gruvbox-material-vscode)
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_bg = "#2a2827"
idle_fg = "#ddc7a1"
info_bg = "#7daea3"
info_fg = "#202020"
good_bg = "#a9b665"
good_fg = "#202020"
warning_bg = "#d8a657"
warning_fg = "#202020"
critical_bg = "#ea6962"
critical_fg = "#202020"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
