# Base16 Katy (powerline)
# Author: George Essig (https://github.com/gessig)
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_bg = "#444267"
idle_fg = "#959dcb"
info_bg = "#82aaff"
info_fg = "#292d3e"
good_bg = "#78c06e"
good_fg = "#292d3e"
warning_bg = "#e0a557"
warning_fg = "#292d3e"
critical_bg = "#6e98e1"
critical_fg = "#292d3e"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
