# Base16 Monokai (powerline)
# Author: Wimer Hazenberg (http://www.monokai.nl)
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_bg = "#383830"
idle_fg = "#f8f8f2"
info_bg = "#66d9ef"
info_fg = "#272822"
good_bg = "#a6e22e"
good_fg = "#272822"
warning_bg = "#f4bf75"
warning_fg = "#272822"
critical_bg = "#f92672"
critical_fg = "#272822"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
