# Base16 Unikitty Light (powerline)
# Author: Josh W Lewis (@joshwlewis)
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_bg = "#e1e1e2"
idle_fg = "#6c696e"
info_bg = "#775dff"
info_fg = "#ffffff"
good_bg = "#17ad98"
good_fg = "#ffffff"
warning_bg = "#dc8a0e"
warning_fg = "#ffffff"
critical_bg = "#d8137f"
critical_fg = "#ffffff"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
