# Base16 Everforest (powerline)
# Author: Sainnhe Park (https://github.com/sainnhe)
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_bg = "#374247"
idle_fg = "#d3c6aa"
info_bg = "#a7c080"
info_fg = "#2f383e"
good_bg = "#83c092"
good_fg = "#2f383e"
warning_bg = "#dbbc7f"
warning_fg = "#2f383e"
critical_bg = "#7fbbb3"
critical_fg = "#2f383e"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
