# Base16 Sakura (powerline)
# Author: Misterio77 (http://github.com/Misterio77)
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_bg = "#f8e2e7"
idle_fg = "#564448"
info_bg = "#006e93"
info_fg = "#feedf3"
good_bg = "#2e916d"
good_fg = "#feedf3"
warning_bg = "#c29461"
warning_fg = "#feedf3"
critical_bg = "#df2d52"
critical_fg = "#feedf3"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
