# Base16 Nebula (powerline)
# Author: Gabriel Fontes (https://github.com/Misterio77)
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_bg = "#414f60"
idle_fg = "#a4a6a9"
info_bg = "#4d6bb6"
info_fg = "#22273b"
good_bg = "#6562a8"
good_fg = "#22273b"
warning_bg = "#4f9062"
warning_fg = "#22273b"
critical_bg = "#777abc"
critical_fg = "#22273b"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
