# Base16 Material Darker (powerline)
# Author: Nate Peterson
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_bg = "#303030"
idle_fg = "#eeffff"
info_bg = "#82aaff"
info_fg = "#212121"
good_bg = "#c3e88d"
good_fg = "#212121"
warning_bg = "#ffcb6b"
warning_fg = "#212121"
critical_bg = "#f07178"
critical_fg = "#212121"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
