# Base16 Atelier Estuary Light (powerline)
# Author: Bram de Haan (http://atelierbramdehaan.nl)
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_bg = "#e7e6df"
idle_fg = "#5f5e4e"
info_bg = "#36a166"
info_fg = "#f4f3ec"
good_bg = "#7d9726"
good_fg = "#f4f3ec"
warning_bg = "#a5980d"
warning_fg = "#f4f3ec"
critical_bg = "#ba6236"
critical_fg = "#f4f3ec"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
