# Base16 Rebecca (powerline)
# Author: Victor Borja (http://github.com/vic) based on Rebecca Theme (http://github.com/vic/rebecca-theme)
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_bg = "#663399"
idle_fg = "#f1eff8"
info_bg = "#2de0a7"
info_fg = "#292a44"
good_bg = "#6dfedf"
good_fg = "#292a44"
warning_bg = "#ae81ff"
warning_fg = "#292a44"
critical_bg = "#a0a0c5"
critical_fg = "#292a44"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
