# Base16 Humanoid dark (powerline)
# Author: Thomas (tasmo) Friese
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_bg = "#333b3d"
idle_fg = "#f8f8f2"
info_bg = "#00a6fb"
info_fg = "#232629"
good_bg = "#02d849"
good_fg = "#232629"
warning_bg = "#ffb627"
warning_fg = "#232629"
critical_bg = "#f11235"
critical_fg = "#232629"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
