# Base16 ShadeSmear Light (powerline)
# Author: Kyle Giammarco (http://kyle.giammar.co)
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_bg = "#e4e4e4"
idle_fg = "#232323"
info_bg = "#376388"
info_fg = "#dbdbdb"
good_bg = "#71983b"
good_fg = "#dbdbdb"
warning_bg = "#307878"
warning_fg = "#dbdbdb"
critical_bg = "#cc5450"
critical_fg = "#dbdbdb"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
