# Base16 Hopscotch (powerline)
# Author: Jan T. Sott
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_bg = "#433b42"
idle_fg = "#b9b5b8"
info_bg = "#1290bf"
info_fg = "#322931"
good_bg = "#8fc13e"
good_fg = "#322931"
warning_bg = "#fdcc59"
warning_fg = "#322931"
critical_bg = "#dd464c"
critical_fg = "#322931"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
