# Base16 Chalk (powerline)
# Author: Chris Kempson (http://chriskempson.com)
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_bg = "#202020"
idle_fg = "#d0d0d0"
info_bg = "#6fc2ef"
info_fg = "#151515"
good_bg = "#acc267"
good_fg = "#151515"
warning_bg = "#ddb26f"
warning_fg = "#151515"
critical_bg = "#fb9fb1"
critical_fg = "#151515"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
