# Base16 Woodland (powerline)
# Author: Jay Cornwall (https://jcornwall.com)
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_bg = "#302b25"
idle_fg = "#cabcb1"
info_bg = "#88a4d3"
info_fg = "#231e18"
good_bg = "#b7ba53"
good_fg = "#231e18"
warning_bg = "#e0ac16"
warning_fg = "#231e18"
critical_bg = "#d35c5c"
critical_fg = "#231e18"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
