# Base16 Silk Dark (powerline)
# Author: Gabriel Fontes (https://github.com/Misterio77)
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_bg = "#1d494e"
idle_fg = "#c7dbdd"
info_bg = "#46bddd"
info_fg = "#0e3c46"
good_bg = "#73d8ad"
good_fg = "#0e3c46"
warning_bg = "#fce380"
warning_fg = "#0e3c46"
critical_bg = "#fb6953"
critical_fg = "#0e3c46"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
