# Base16 Spaceduck (powerline)
# Author: Guillermo Rodriguez (https://github.com/pineapplegiant), packaged by Gabriel Fontes (https://github.com/Misterio77)
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_bg = "#1b1c36"
idle_fg = "#ecf0c1"
info_bg = "#7a5ccc"
info_fg = "#16172d"
good_bg = "#5ccc96"
good_fg = "#16172d"
warning_bg = "#f2ce00"
warning_fg = "#16172d"
critical_bg = "#e33400"
critical_fg = "#16172d"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
