# Base16 vulcan (powerline)
# Author: Andrey Varfolomeev
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_bg = "#122339"
idle_fg = "#5b778c"
info_bg = "#977d7c"
info_fg = "#041523"
good_bg = "#977d7c"
good_fg = "#041523"
warning_bg = "#adb4b9"
warning_fg = "#041523"
critical_bg = "#818591"
critical_fg = "#041523"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
