# Base16 selenized-black (powerline)
# Author: Jan Warchol (https://github.com/jan-warchol/selenized) / adapted to base16 by ali
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_bg = "#252525"
idle_fg = "#b9b9b9"
info_bg = "#368aeb"
info_fg = "#181818"
good_bg = "#70b433"
good_fg = "#181818"
warning_bg = "#dbb32d"
warning_fg = "#181818"
critical_bg = "#ed4a46"
critical_fg = "#181818"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
