# Base16 Tokyo Night Terminal Light (powerline)
# Author: Michaël Ball
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_bg = "#cbccd1"
idle_fg = "#4c505e"
info_bg = "#34548a"
info_fg = "#d5d6db"
good_bg = "#33635c"
good_fg = "#d5d6db"
warning_bg = "#8f5e15"
warning_fg = "#d5d6db"
critical_bg = "#8c4351"
critical_fg = "#d5d6db"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
