# Base16 Sagelight (powerline)
# Author: Carter Veldhuizen
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_bg = "#e8e8e8"
idle_fg = "#383838"
info_bg = "#a0a7d2"
info_fg = "#f8f8f8"
good_bg = "#a0d2c8"
good_fg = "#f8f8f8"
warning_bg = "#ffdc61"
warning_fg = "#f8f8f8"
critical_bg = "#fa8480"
critical_fg = "#f8f8f8"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
