# Base16 DanQing (powerline)
# Author: Wenhan Zhu (Cosmos) (zhuwenhan950913@gmail.com)
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_bg = "#434846"
idle_fg = "#e0f0ef"
info_bg = "#b0a4e3"
info_fg = "#2d302f"
good_bg = "#8ab361"
good_fg = "#2d302f"
warning_bg = "#f0c239"
warning_fg = "#2d302f"
critical_bg = "#f9906f"
critical_fg = "#2d302f"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
