# Base16 OneDark (powerline)
# Author: Lalit Magant (http://github.com/tilal6991)
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_bg = "#353b45"
idle_fg = "#abb2bf"
info_bg = "#61afef"
info_fg = "#282c34"
good_bg = "#98c379"
good_fg = "#282c34"
warning_bg = "#e5c07b"
warning_fg = "#282c34"
critical_bg = "#e06c75"
critical_fg = "#282c34"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
