# Base16 Paraiso (powerline)
# Author: Jan T. Sott
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_bg = "#41323f"
idle_fg = "#a39e9b"
info_bg = "#06b6ef"
info_fg = "#2f1e2e"
good_bg = "#48b685"
good_fg = "#2f1e2e"
warning_bg = "#fec418"
warning_fg = "#2f1e2e"
critical_bg = "#ef6155"
critical_fg = "#2f1e2e"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
