# Base16 Solarized Dark (powerline)
# Author: Ethan Schoonover (modified by aramisgithub)
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_bg = "#073642"
idle_fg = "#93a1a1"
info_bg = "#268bd2"
info_fg = "#002b36"
good_bg = "#859900"
good_fg = "#002b36"
warning_bg = "#b58900"
warning_fg = "#002b36"
critical_bg = "#dc322f"
critical_fg = "#002b36"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
