# Base16 Hardcore (powerline)
# Author: Chris Caller
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_bg = "#303030"
idle_fg = "#cdcdcd"
info_bg = "#66d9ef"
info_fg = "#212121"
good_bg = "#a6e22e"
good_fg = "#212121"
warning_bg = "#e6db74"
warning_fg = "#212121"
critical_bg = "#f92672"
critical_fg = "#212121"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
