# Base16 Solarized Light (powerline)
# Author: Ethan Schoonover (modified by aramisgithub)
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_bg = "#eee8d5"
idle_fg = "#586e75"
info_bg = "#268bd2"
info_fg = "#fdf6e3"
good_bg = "#859900"
good_fg = "#fdf6e3"
warning_bg = "#b58900"
warning_fg = "#fdf6e3"
critical_bg = "#dc322f"
critical_fg = "#fdf6e3"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
