# Base16 Grayscale Dark (powerline)
# Author: Alexandre Gavioli (https://github.com/Alexx2/)
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_bg = "#252525"
idle_fg = "#b9b9b9"
info_bg = "#686868"
info_fg = "#101010"
good_bg = "#8e8e8e"
good_fg = "#101010"
warning_bg = "#a0a0a0"
warning_fg = "#101010"
critical_bg = "#7c7c7c"
critical_fg = "#101010"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
