# Base16 Solar Flare Light (powerline)
# Author: Chuck Harmston (https://chuck.harmston.ch)
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_bg = "#e8e9ed"
idle_fg = "#586875"
info_bg = "#33b5e1"
info_fg = "#f5f7fa"
good_bg = "#7cc844"
good_fg = "#f5f7fa"
warning_bg = "#e4b51c"
warning_fg = "#f5f7fa"
critical_bg = "#ef5253"
critical_fg = "#f5f7fa"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
