# Base16 Mocha (powerline)
# Author: Chris Kempson (http://chriskempson.com)
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_bg = "#534636"
idle_fg = "#d0c8c6"
info_bg = "#8ab3b5"
info_fg = "#3b3228"
good_bg = "#beb55b"
good_fg = "#3b3228"
warning_bg = "#f4bc87"
warning_fg = "#3b3228"
critical_bg = "#cb6077"
critical_fg = "#3b3228"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
