# Base16 Bespin (powerline)
# Author: Jan T. Sott
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_bg = "#36312e"
idle_fg = "#8a8986"
info_bg = "#5ea6ea"
info_fg = "#28211c"
good_bg = "#54be0d"
good_fg = "#28211c"
warning_bg = "#f9ee98"
warning_fg = "#28211c"
critical_bg = "#cf6a4c"
critical_fg = "#28211c"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
