# Base16 Windows NT (powerline)
# Author: Fergus Collins (https://github.com/C-Fergus)
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_bg = "#2a2a2a"
idle_fg = "#c0c0c0"
info_bg = "#0000ff"
info_fg = "#000000"
good_bg = "#00ff00"
good_fg = "#000000"
warning_bg = "#ffff00"
warning_fg = "#000000"
critical_bg = "#ff0000"
critical_fg = "#000000"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
