# Base16 UwUnicorn (powerline)
# Author: Fernando Marques (https://github.com/RakkiUwU) and Gabriel Fontes (https://github.com/Misterio77)
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_bg = "#2f2a3f"
idle_fg = "#eed5d9"
info_bg = "#6a9eb5"
info_fg = "#241b26"
good_bg = "#c965bf"
good_fg = "#241b26"
warning_bg = "#a84a73"
warning_fg = "#241b26"
critical_bg = "#877bb6"
critical_fg = "#241b26"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
