# Base16 Atelier Seaside (powerline)
# Author: Bram de Haan (http://atelierbramdehaan.nl)
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_bg = "#242924"
idle_fg = "#8ca68c"
info_bg = "#3d62f5"
info_fg = "#131513"
good_bg = "#29a329"
good_fg = "#131513"
warning_bg = "#98981b"
warning_fg = "#131513"
critical_bg = "#e6193c"
critical_fg = "#131513"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
