# Base16 Atelier Cave (powerline)
# Author: Bram de Haan (http://atelierbramdehaan.nl)
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_bg = "#26232a"
idle_fg = "#8b8792"
info_bg = "#576ddb"
info_fg = "#19171c"
good_bg = "#2a9292"
good_fg = "#19171c"
warning_bg = "#a06e3b"
warning_fg = "#19171c"
critical_bg = "#be4678"
critical_fg = "#19171c"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
