# Base16 Railscasts (powerline)
# Author: Ryan Bates (http://railscasts.com)
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_bg = "#272935"
idle_fg = "#e6e1dc"
info_bg = "#6d9cbe"
info_fg = "#2b2b2b"
good_bg = "#a5c261"
good_fg = "#2b2b2b"
warning_bg = "#ffc66d"
warning_fg = "#2b2b2b"
critical_bg = "#da4939"
critical_fg = "#2b2b2b"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
