# Base16 Gruvbox Material Light, Soft (powerline)
# Author: Mayush Kumar (https://github.com/MayushKumar), sainnhe (https://github.com/sainnhe/gruvbox-material-vscode)
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_bg = "#ebdbb2"
idle_fg = "#654735"
info_bg = "#45707a"
info_fg = "#f2e5bc"
good_bg = "#6c782e"
good_fg = "#f2e5bc"
warning_bg = "#b47109"
warning_fg = "#f2e5bc"
critical_bg = "#c14a4a"
critical_fg = "#f2e5bc"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
