# Base16 summercamp (powerline)
# Author: zoe firi (zoefiri.github.io)
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_bg = "#2a261c"
idle_fg = "#736e55"
info_bg = "#489bf0"
info_fg = "#1c1810"
good_bg = "#5ceb5a"
good_fg = "#1c1810"
warning_bg = "#f2ff27"
warning_fg = "#1c1810"
critical_bg = "#e35142"
critical_fg = "#1c1810"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
