# Base16 Seti UI (powerline)
# Author: 
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_bg = "#282a2b"
idle_fg = "#d6d6d6"
info_bg = "#55b5db"
info_fg = "#151718"
good_bg = "#9fca56"
good_fg = "#151718"
warning_bg = "#e6cd69"
warning_fg = "#151718"
critical_bg = "#cd3f45"
critical_fg = "#151718"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
