# Base16 Solar Flare (powerline)
# Author: Chuck Harmston (https://chuck.harmston.ch)
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_bg = "#222e38"
idle_fg = "#a6afb8"
info_bg = "#33b5e1"
info_fg = "#18262f"
good_bg = "#7cc844"
good_fg = "#18262f"
warning_bg = "#e4b51c"
warning_fg = "#18262f"
critical_bg = "#ef5253"
critical_fg = "#18262f"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
