# Base16 Colors (powerline)
# Author: mrmrs (http://clrs.cc)
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_bg = "#333333"
idle_fg = "#bbbbbb"
info_bg = "#0074d9"
info_fg = "#111111"
good_bg = "#2ecc40"
good_fg = "#111111"
warning_bg = "#ffdc00"
warning_fg = "#111111"
critical_bg = "#ff4136"
critical_fg = "#111111"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
