# Base16 Darcula (powerline)
# Author: jetbrains
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_bg = "#323232"
idle_fg = "#a9b7c6"
info_bg = "#9876aa"
info_fg = "#2b2b2b"
good_bg = "#6a8759"
good_fg = "#2b2b2b"
warning_bg = "#bbb529"
warning_fg = "#2b2b2b"
critical_bg = "#4eade5"
critical_fg = "#2b2b2b"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
