# Base16 Mellow Purple (powerline)
# Author: gidsi
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_bg = "#1a092d"
idle_fg = "#ffeeff"
info_bg = "#550068"
info_fg = "#1e0528"
good_bg = "#05cb0d"
good_fg = "#1e0528"
warning_bg = "#955ae7"
warning_fg = "#1e0528"
critical_bg = "#00d9e9"
critical_fg = "#1e0528"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
