# Base16 Ocean (powerline)
# Author: Chris Kempson (http://chriskempson.com)
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_bg = "#343d46"
idle_fg = "#c0c5ce"
info_bg = "#8fa1b3"
info_fg = "#2b303b"
good_bg = "#a3be8c"
good_fg = "#2b303b"
warning_bg = "#ebcb8b"
warning_fg = "#2b303b"
critical_bg = "#bf616a"
critical_fg = "#2b303b"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
