# Base16 Grayscale Light (powerline)
# Author: Alexandre Gavioli (https://github.com/Alexx2/)
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_bg = "#e3e3e3"
idle_fg = "#464646"
info_bg = "#686868"
info_fg = "#f7f7f7"
good_bg = "#8e8e8e"
good_fg = "#f7f7f7"
warning_bg = "#a0a0a0"
warning_fg = "#f7f7f7"
critical_bg = "#7c7c7c"
critical_fg = "#f7f7f7"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
