# Base16 Pasque (powerline)
# Author: Gabriel Fontes (https://github.com/Misterio77)
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_bg = "#100323"
idle_fg = "#dedcdf"
info_bg = "#8e7dc6"
info_fg = "#271c3a"
good_bg = "#c6914b"
good_fg = "#271c3a"
warning_bg = "#804ead"
warning_fg = "#271c3a"
critical_bg = "#a92258"
critical_fg = "#271c3a"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
