# Base16 selenized-white (powerline)
# Author: Jan Warchol (https://github.com/jan-warchol/selenized) / adapted to base16 by ali
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_bg = "#ebebeb"
idle_fg = "#474747"
info_bg = "#0054cf"
info_fg = "#ffffff"
good_bg = "#008400"
good_fg = "#ffffff"
warning_bg = "#af8500"
warning_fg = "#ffffff"
critical_bg = "#bf0000"
critical_fg = "#ffffff"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
