# Base16 Rosé Pine Dawn (powerline)
# Author: Emilia Dunfelt &lt;sayhi@dunfelt.se&gt;
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_bg = "#fffaf3"
idle_fg = "#575279"
info_bg = "#56949f"
info_fg = "#faf4ed"
good_bg = "#d7827e"
good_fg = "#faf4ed"
warning_bg = "#ea9d34"
warning_fg = "#faf4ed"
critical_bg = "#1f1d2e"
critical_fg = "#faf4ed"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
