# Base16 Pico (powerline)
# Author: PICO-8 (http://www.lexaloffle.com/pico-8.php)
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_bg = "#1d2b53"
idle_fg = "#5f574f"
info_bg = "#83769c"
info_fg = "#000000"
good_bg = "#00e756"
good_fg = "#000000"
warning_bg = "#fff024"
warning_fg = "#000000"
critical_bg = "#ff004d"
critical_fg = "#000000"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
