# Base16 Tomorrow (powerline)
# Author: Chris Kempson (http://chriskempson.com)
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_bg = "#e0e0e0"
idle_fg = "#4d4d4c"
info_bg = "#4271ae"
info_fg = "#ffffff"
good_bg = "#718c00"
good_fg = "#ffffff"
warning_bg = "#eab700"
warning_fg = "#ffffff"
critical_bg = "#c82829"
critical_fg = "#ffffff"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
