# Base16 Classic Light (powerline)
# Author: Jason Heeris (http://heeris.id.au)
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_bg = "#e0e0e0"
idle_fg = "#303030"
info_bg = "#6a9fb5"
info_fg = "#f5f5f5"
good_bg = "#90a959"
good_fg = "#f5f5f5"
warning_bg = "#f4bf75"
warning_fg = "#f5f5f5"
critical_bg = "#ac4142"
critical_fg = "#f5f5f5"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
