# Base16 Atelier Dune Light (powerline)
# Author: Bram de Haan (http://atelierbramdehaan.nl)
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_bg = "#e8e4cf"
idle_fg = "#6e6b5e"
info_bg = "#6684e1"
info_fg = "#fefbec"
good_bg = "#60ac39"
good_fg = "#fefbec"
warning_bg = "#ae9513"
warning_fg = "#fefbec"
critical_bg = "#d73737"
critical_fg = "#fefbec"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
