# Base16 Gruvbox dark, soft (powerline)
# Author: Dawid Kurek (dawikur@gmail.com), morhetz (https://github.com/morhetz/gruvbox)
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_bg = "#3c3836"
idle_fg = "#d5c4a1"
info_bg = "#83a598"
info_fg = "#32302f"
good_bg = "#b8bb26"
good_fg = "#32302f"
warning_bg = "#fabd2f"
warning_fg = "#32302f"
critical_bg = "#fb4934"
critical_fg = "#32302f"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
