# Base16 selenized-dark (powerline)
# Author: Jan Warchol (https://github.com/jan-warchol/selenized) / adapted to base16 by ali
# Template Author: gnsfujiwara (https://github.com/gnsfujiwara)

idle_bg = "#184956"
idle_fg = "#adbcbc"
info_bg = "#4695f7"
info_fg = "#103c48"
good_bg = "#75b938"
good_fg = "#103c48"
warning_bg = "#dbb32d"
warning_fg = "#103c48"
critical_bg = "#fa5750"
critical_fg = "#103c48"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
